version: '3.5'

services:
  web:
    image: vehicleinventoryapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - ASPNETCORE_HTTP_PORT=5056
      - ConnectionStrings__DefaultConnection=Host=db;Database=trucksdb;Username=dbuser;Password=dbpassword1
    ports:
      - "5056:80"
    depends_on:
      - db
    networks:
      - app-cluster

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword1
      POSTGRES_DB: truckbd
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-cluster

volumes:
  dbdata:

networks:
  app-cluster: